### ISSUE TITLE
Unit error for E_Ryd in cloudy17

### ISSUE THREAD

**Issue by newmansoph** [flaresimulations/synthesizer-grids#12]
I'm getting an error in cloudy17 with the line `E_Ryd = E.to("Ry").value` . The error says `Cannot convert between 'kg*m/s**2' (dim '(length)*(mass)/(time)**2') and 'Ry' (dim '(length)**2*(mass)/(time)**2')`

**Comment by christopherlovell** [comment]
Should be fixed in #13
