### ISSUE TITLE
No pre-commit-config file in this repo

### ISSUE THREAD

**Issue by teresamatamoro** [flaresimulations/synthesizer-grids#69]
The Contributing.md instructions specify to set up pre-commit hooks, however this repo is missing the necessary .pre-commit-config.yaml file to do so.

**Comment by WillJRoper** [comment]
Good point, another good reason this should not be outside the main repo :|. I can't fix this now but will add in the necessary config to get it working.

**Comment by WillJRoper** [comment]
Another thing to note: running the pre-commit-hook on this repo may not go well... since the code is far from clean in this repo (and issue I wish I could fix but don't currently have the time).
